In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('Experimental Data.csv')
df.describe()

,Cellulose,Hemicellulose,Lignin,Solids Loading [g/L],Enzyme Loading [g/L],Time [h],Glucose Concentration [g/L],Xylose Concentration [g/L],Cellobiose Concentration [g/L]
count,7.000000e+01,7.000000e+01,7.000000e+01,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,6.600000e-01,8.300000e-02,2.520000e-01,157.857143,0.365171,21.942857,34.448586,5.623629,0.768386
std,3.354718e-16,1.397799e-17,1.118239e-16,18.328157,0.282183,27.154889,23.640194,3.781434,0.628498
min,6.600000e-01,8.300000e-02,2.520000e-01,150.000000,0.088000,0.000000,0.000000,0.000000,0.000000
25%,6.600000e-01,8.300000e-02,2.520000e-01,150.000000,0.175000,2.000000,12.302500,2.564000,0.098750
50%,6.600000e-01,8.300000e-02,2.520000e-01,150.000000,0.263000,8.000000,37.254000,5.519500,0.885500
75%,6.600000e-01,8.300000e-02,2.520000e-01,150.000000,0.438000,42.000000,54.759500,8.864000,1.258000
max,6.600000e-01,8.300000e-02,2.520000e-01,200.000000,1.050000,96.000000,84.520000,11.988000,2.192000

In [ ]:
df_synthetic = pd.read_csv('synthetic_hydrolysis_data_LHS.csv')
df_synthetic.describe()

,Cellulose,Hemicellulose,Lignin,Solids Loading [g/L],Enzyme Loading [g/L],Time [h],Glucose Concentration [g/L],Xylose Concentration [g/L],Cellobiose Concentration [g/L]
count,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000,1100.000000
mean,0.615380,0.116030,0.268620,149.161370,0.658090,24.818182,30.267747,10.919988,1.215149
std,0.024832,0.025127,0.024222,55.641246,0.322175,31.304133,24.163087,8.294621,1.131750
min,0.554000,0.058000,0.208000,55.737000,0.053000,0.000000,0.000000,0.000000,0.000000
25%,0.601750,0.099250,0.251500,99.630750,0.382750,2.000000,12.720000,4.414500,0.346000
50%,0.619000,0.118500,0.274500,154.916000,0.692000,8.000000,24.138000,9.278500,0.886500
75%,0.636000,0.138000,0.289250,196.839750,0.933750,48.000000,42.539500,16.071250,1.789500
max,0.649000,0.150000,0.299000,247.855000,1.195000,96.000000,135.558000,35.674000,5.569000

: